# Generated by Django 5.1.4 on 2026-05-12 09:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_05b4bc_idx',
            old_name='notification_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_f2ad08_idx',
            old_name='notification_user_unread_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_6c61ca_idx',
            old_name='notification_user_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_notific_f2e0f7_idx',
            old_name='notification_type_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_priorit_3fc670_idx',
            old_name='notification_priority_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When notification was created'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional expiration for promotional/temporary notifications', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for data retention'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether user has seen this notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Type-specific data (order_id, product_id, tracking_info, etc.)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER_CONFIRMED', 'Order Confirmed'), ('PAYMENT_RECEIVED', 'Payment Received'), ('ORDER_SHIPPED', 'Order Shipped'), ('DELIVERY_UPDATE', 'Delivery Update'), ('DELIVERED', 'Delivered Successfully'), ('DELIVERY_FAILED', 'Failed Delivery Attempt'), ('RESTOCKED_ITEM', 'Item Restocked'), ('ADMIN_MESSAGE', 'Admin Message'), ('WARRANTY_UPDATE', 'Warranty/Support Update'), ('REFUND_STATUS', 'Refund Status'), ('INVOICE_READY', 'Invoice Ready'), ('DELIVERY_ETA', 'Delivery ETA'), ('LOYALTY_POINTS', 'Loyalty/Reward Points'), ('REVIEW_REMINDER', 'Review Reminder')], db_index=True, help_text='Type determines automatic trigger and context', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', help_text='Priority level affects UI highlighting', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when notification was marked as read', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(help_text='Brief notification title (displayed in dropdown)', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='User receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='delivery_attempts',
            field=models.IntegerField(default=0, help_text='Number of delivery attempts', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='delivery_status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='CREATED', help_text='Current delivery status', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='last_error',
            field=models.TextField(blank=True, help_text='Last error message if delivery failed'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification',
            field=models.OneToOneField(help_text='Associated notification', on_delete=django.db.models.deletion.CASCADE, related_name='log', to='notifications.notification'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='websocket_delivered',
            field=models.BooleanField(default=False, help_text='Whether delivered via WebSocket'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='admin_notifications',
            field=models.BooleanField(default=True, help_text='Receive messages from administrators'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='order_notifications',
            field=models.BooleanField(default=True, help_text='Receive order confirmation, shipped, delivered notifications'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='promotional_notifications',
            field=models.BooleanField(default=True, help_text='Receive promotional and loyalty point notifications'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=False, help_text='Whether quiet hours are enabled'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, help_text='End time for quiet hours (e.g., 08:00)', null=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, help_text='Start time for quiet hours (e.g., 22:00)', null=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='support_notifications',
            field=models.BooleanField(default=True, help_text='Receive warranty and support updates'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(help_text='User whose preferences these are', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL),
        ),
    ]
