# Generated by Django 5.1.4 on 2026-05-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_admin_fields'),
        ('users', '0002_alter_user_email'),
    ]

    operations = [
    ]
