# Generated by Django 5.1.4 on 2026-05-12 09:05

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('staff_admin', 'Staff Admin'), ('support_agent', 'Support Agent'), ('delivery_manager', 'Delivery Manager'), ('customer', 'Customer')], db_index=True, default='customer', help_text='Primary role for admin dashboard access and permissions', max_length=32),
        ),
    ]
