# Generated by Django 5.1.4 on 2026-02-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'ordering': ['-updated_at']},
        ),
    ]
