# Generated by Django 5.1.4 on 2026-05-10 08:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Order', 'verbose_name_plural': 'Customer Orders'},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_status_c6dd84_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='order_created_idx',
            old_name='orders_orde_created_f0ce29_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['email', '-created_at'], name='order_email_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'paid'], name='order_status_paid_idx'),
        ),
    ]
