# Generated by Django 5.0 on 2025-12-20 18:10

from django.db import migrations, models
import django.utils.timezone


def migrate_replied_to_status(apps, schema_editor):
    """Migrate old 'replied' boolean field to new 'status' field."""
    UserMessage = apps.get_model('user_messages', 'UserMessage')
    # Update existing records: replied=True -> status='replied', replied=False -> status='new'
    UserMessage.objects.filter(replied=True).update(status='replied')
    UserMessage.objects.filter(replied=False).update(status='new')


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        # Add new status field
        migrations.AddField(
            model_name='usermessage',
            name='status',
            field=models.CharField(
                choices=[
                    ('new', 'New'),
                    ('read', 'Read'),
                    ('replied', 'Replied'),
                    ('resolved', 'Resolved')
                ],
                default='new',
                max_length=20
            ),
        ),
        # Add replied_at timestamp
        migrations.AddField(
            model_name='usermessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Add updated_at timestamp
        migrations.AddField(
            model_name='usermessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Migrate data from old 'replied' field to new 'status' field
        migrations.RunPython(migrate_replied_to_status, migrations.RunPython.noop),
        # Remove old 'replied' boolean field
        migrations.RemoveField(
            model_name='usermessage',
            name='replied',
        ),
        # Add index for performance
        migrations.AddIndex(
            model_name='usermessage',
            index=models.Index(fields=['status', '-created_at'], name='user_messag_status_created_idx'),
        ),
    ]
