# Generated by Django 5.1.4 on 2026-05-10 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Message', 'verbose_name_plural': 'Customer Messages'},
        ),
        migrations.RenameIndex(
            model_name='usermessage',
            new_name='msg_status_created_idx',
            old_name='user_messag_status_idx',
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='reply_text',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('resolved', 'Resolved')], db_index=True, default='new', max_length=20),
        ),
        migrations.AddIndex(
            model_name='usermessage',
            index=models.Index(fields=['email', '-created_at'], name='msg_email_created_idx'),
        ),
    ]
