# Generated by Django 5.0 on 2025-12-20 18:13

from django.db import migrations


def update_table_schema(apps, schema_editor):
    """Update existing table schema to match new model."""
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Add status column if it doesn't exist
            cursor.execute("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'user_messages_usermessage' AND column_name = 'status'
                    ) THEN
                        ALTER TABLE user_messages_usermessage 
                        ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'new';
                    END IF;
                END $$;
            """)
            
            # Migrate replied boolean to status
            cursor.execute("""
                UPDATE user_messages_usermessage 
                SET status = CASE WHEN replied = true THEN 'replied' ELSE 'new' END
                WHERE status = 'new';
            """)
            
            # Add replied_at column if it doesn't exist
            cursor.execute("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'user_messages_usermessage' AND column_name = 'replied_at'
                    ) THEN
                        ALTER TABLE user_messages_usermessage 
                        ADD COLUMN replied_at TIMESTAMP WITH TIME ZONE NULL;
                    END IF;
                END $$;
            """)
            
            # Add updated_at column if it doesn't exist
            cursor.execute("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'user_messages_usermessage' AND column_name = 'updated_at'
                    ) THEN
                        ALTER TABLE user_messages_usermessage 
                        ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
                    END IF;
                END $$;
            """)
            
            # Drop old replied column
            cursor.execute("""
                ALTER TABLE user_messages_usermessage DROP COLUMN IF EXISTS replied;
            """)
            
            # Create index
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS user_messag_status_40ef99_idx 
                ON user_messages_usermessage (status, created_at DESC);
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_table_schema, migrations.RunPython.noop),
    ]
