# Generated by Django 5.1.4 on 2026-05-10 08:29

import django.db.models.deletion
from django.db import migrations, models


def clear_admin_user_values(apps, schema_editor):
    AdminAuditLog = apps.get_model('pgf_admin', 'AdminAuditLog')
    AdminAuditLog.objects.all().update(admin_user=None)


class Migration(migrations.Migration):

    dependencies = [
        ('pgf_admin', '0001_initial'),
        ('users', '0004_alter_user_options_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_admin_user_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='adminauditlog',
            name='admin_user',
            field=models.ForeignKey(
                blank=True,
                help_text='Admin user who performed the action',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='admin_audit_logs',
                to='users.user',
            ),
        ),
    ]
