# Generated by Django 5.1.4 on 2026-05-12 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0002_alter_order_options_and_more'),
        ('pgf_admin', '0003_convert_django_admin_log_user_to_uuid'),
        ('products', '0002_alter_product_category_alter_product_featured_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('staff_admin', 'Staff Admin'), ('support_agent', 'Support Agent'), ('delivery_manager', 'Delivery Manager')], default='staff_admin', max_length=20)),
                ('can_manage_products', models.BooleanField(default=False)),
                ('can_manage_orders', models.BooleanField(default=False)),
                ('can_manage_customers', models.BooleanField(default=False)),
                ('can_manage_support', models.BooleanField(default=False)),
                ('can_manage_delivery', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=False)),
                ('can_manage_settings', models.BooleanField(default=False)),
                ('can_manage_coupons', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Role',
                'verbose_name_plural': 'Admin Roles',
                'db_table': 'admin_roles',
            },
        ),
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_title', models.CharField(default='Pie Global Admin Dashboard', max_length=255)),
                ('logo_url', models.URLField(blank=True)),
                ('favicon_url', models.URLField(blank=True)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('sms_notifications_enabled', models.BooleanField(default=False)),
                ('items_per_page', models.PositiveIntegerField(default=25)),
                ('search_debounce_ms', models.PositiveIntegerField(default=300)),
                ('dark_mode_enabled', models.BooleanField(default=False)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text='Alert when product stock falls below this')),
                ('high_order_alert_threshold', models.PositiveIntegerField(default=100, help_text='Alert when order total exceeds this')),
                ('max_refund_without_approval', models.DecimalField(decimal_places=2, default=500.0, help_text='Refunds above this require approval', max_digits=10)),
                ('enable_support_tickets', models.BooleanField(default=True)),
                ('enable_review_requests', models.BooleanField(default=True)),
                ('enable_delivery_tracking', models.BooleanField(default=True)),
                ('enable_coupons', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Settings',
                'verbose_name_plural': 'Dashboard Settings',
                'db_table': 'dashboard_settings',
            },
        ),
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(db_index=True, default=False)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review Request',
                'verbose_name_plural': 'Review Requests',
                'db_table': 'review_requests',
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_stock', models.PositiveIntegerField()),
                ('threshold', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Stock Alert',
                'verbose_name_plural': 'Stock Alerts',
                'db_table': 'stock_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='adminauditlog',
            name='audit_type_time_idx',
        ),
        migrations.RenameIndex(
            model_name='adminauditlog',
            new_name='admin_audit_admin_u_06fe08_idx',
            old_name='audit_user_time_idx',
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='object_repr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('status_change', 'Status Changed'), ('marked_paid', 'Marked as Paid'), ('message_reply', 'Message Replied'), ('message_resolved', 'Message Resolved'), ('media_upload', 'Media Uploaded'), ('media_delete', 'Media Deleted')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['content_type', 'action', '-timestamp'], name='admin_audit_content_b9c27e_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['-timestamp'], name='admin_audit_timesta_5c0429_idx'),
        ),
        migrations.AlterModelTable(
            name='adminauditlog',
            table='admin_audit_logs',
        ),
        migrations.AddField(
            model_name='adminrole',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_request', to='orders.order'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reviewrequest',
            index=models.Index(fields=['is_sent', '-created_at'], name='review_requ_is_sent_e786cc_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewrequest',
            index=models.Index(fields=['-created_at'], name='review_requ_created_2cfeaa_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['is_active', '-created_at'], name='stock_alert_is_acti_83a3d2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['product', 'is_active'], name='stock_alert_product_d317cc_idx'),
        ),
    ]
