# Generated by Django 5.0 on 2025-11-20 08:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price for showing discounts', max_digits=12, null=True)),
                ('category', models.CharField(choices=[('sofa', 'Sofa'), ('bed', 'Bed'), ('table', 'Table'), ('wardrobe', 'Wardrobe'), ('office', 'Office Furniture'), ('dining', 'Dining'), ('outdoor', 'Outdoor'), ('storage', 'Storage'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('tags', models.JSONField(blank=True, help_text='Array of tags for filtering', null=True)),
                ('main_image', models.ImageField(blank=True, upload_to='products/main/')),
                ('gallery', models.JSONField(blank=True, help_text='Array of additional image URLs or paths', null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('dimensions', models.CharField(blank=True, help_text="e.g., '200x100x80 cm'", max_length=200)),
                ('material', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', '-created_at'], name='products_pr_categor_4d32d3_idx'), models.Index(fields=['featured', '-created_at'], name='products_pr_feature_8a6f84_idx'), models.Index(fields=['is_active', '-created_at'], name='products_pr_is_acti_645007_idx')],
            },
        ),
    ]
