# Generated by Django 5.1.4 on 2026-04-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sofa', 'Sofa'), ('bed', 'Bed'), ('table', 'Table'), ('wardrobe', 'Wardrobe'), ('office', 'Office Furniture'), ('dining', 'Dining'), ('outdoor', 'Outdoor'), ('storage', 'Storage'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
